---
root: true
#  https://eslint.org/docs/rules/
env:
  node: true
  es2020: true
parserOptions:
  ecmaVersion: 10
globals:
  window: false
  history: false
  Phaser: false
  PrinceJS: false
  document: false
extends:
  - "eslint:recommended"
  - prettier
rules:
  no-var: [error]
  no-unused-vars: [error, { argsIgnorePattern: "data|game|tile" }]
  no-restricted-modules: [error, child_process]
  no-eval: [error]
  no-implied-eval: [error]
  no-console: [error]
  strict: [warn]
  curly: [error]
  no-constant-condition: [error, { checkLoops: false }]
